# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema: https://api-eu-west-2.graphcms.com/v2/ckzzp9r4t83or01zah1z35air/master
    documents:
      - '**/*.gql'
    extensions:
      endpoints:
        default:
          url: https://api-eu-west-2.graphcms.com/v2/ckzzp9r4t83or01zah1z35air/master
      codegen:
        generates:
          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes

        config:
          useTypeImports: true
