# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema: ${VITE_GRAPHQL_API}
    documents:
      - '**/*.gql'
    extensions:
      endpoints:
        default:
          url: ${VITE_GRAPHQL_API}
      codegen:
        generates:
          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes

        config:
          useTypeImports: true
